### PR TITLE
Updating vendor data for Debian stable release of jessie.

### PR DESCRIPTION
**Pull request by mbehrle**

### CODE REVIEW

**Comment by rhertzog** [comment]
Thanks for the patch, merged! Next time you should likely submit the pull request against the repository in https://github.com/saltstack-formulas/debootstrap-formula

**Comment by mbehrle** [comment]
Thx, I did so because saltstack-formulas/debootstrap-formula is forked from rhertzog/debootstrap-formula, so your repos seems to be the master?

**Comment by rhertzog** [comment]
It was the master before it got integrated in saltstack-formulas. Now I consider the one there to be the reference. But I can't drop the link except by removing my own copy...

**Comment by mbehrle** [comment]
Clear to me now. Perhaps it could be worth to drop and re-fork from saltstack-formulas. I think other contributors could search for the master as I did...at least I usually prefer to contribute to the "original" and thus was mislead.

**Pull request merged**
